Repository Amsterdam-Team/Plan-Mate-App, pull requests merged in 2025-05, with the labels that each got.

#23 add test get task usecase
  src/main/kotlin/logic/usecases/task/GetAllTasksByProjectIdUseCase.kt
  src/main/kotlin/logic/usecases/task/GetTaskByIdUseCase.kt
  src/test/kotlin/logic/usecases/task/GetAllTasksByProjectIdUseCaseTest.kt
  src/test/kotlin/logic/usecases/task/GetTaskByIdUseCaseTest.kt
  src/test/kotlin/logic/usecases/task/testFactory/CreateTaskTestFactory.kt
Labels: test

#24 add task delete state usecase
  src/main/kotlin/logic/usecases/state/DeleteStateUseCase.kt
  src/test/kotlin/logic/usecases/state/DeleteStateUseCaseTest.kt
Labels: test

#73 Refactor Create Project UI
  src/main/kotlin/ui/controllers/CreateProjectUIController.kt
  src/test/kotlin/ui/project/CreateProjectUIControllerTest.kt
Labels: enhancement

#72 Refactor Create Project UseCase
  src/main/kotlin/data/repository/project/ProjectRepositoryImpl.kt
  src/main/kotlin/logic/usecases/ValidateInputUseCase.kt
  src/main/kotlin/logic/usecases/project/CreateProjectUseCase.kt
  src/test/kotlin/logic/usecases/project/CreateProjectUseCaseTest.kt
  src/test/kotlin/logic/usecases/testFactory/CreateProjectTestFactory.kt
Labels: enhancement

#100 Urgent viewAllProject bug fix
  src/main/kotlin/data/datasources/projectDataSource/ProjectDataSource.kt
  src/main/kotlin/data/repository/task/TaskRepositoryImpl.kt
  src/main/kotlin/di/appModule.kt
  src/main/kotlin/logic/usecases/project/GetAllProjectsUseCase.kt
  src/main/kotlin/ui/utils/SwimLanesUI.kt
  src/main/kotlin/ui/utils/UIHelperFunctions.kt
  src/test/kotlin/logic/usecases/project/GetAllProjectsUseCaseTest.kt
Labels: bug
